//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjuntos
    {
        public int id { get; set; }
        public string Nombre_Archivo { get; set; }
        public string Ruta_Archivo { get; set; }
        public short estado { get; set; }
        public int Tipo_archivo_id { get; set; }
        public double Tamano { get; set; }
        public string Descripcion { get; set; }
        public int Usuarios_Usuario_id { get; set; }
        public string extension { get; set; }
        public int referencia { get; set; }
        public int Tablas_referencia_id { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
    
        public virtual Tablas_referencia Tablas_referencia { get; set; }
        public virtual Tipo_archivo Tipo_archivo { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
