//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bancos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bancos()
        {
            this.Bancos_Movimientos = new HashSet<Bancos_Movimientos>();
        }
    
        public int id { get; set; }
        public string nombre_banco { get; set; }
        public string numero_cuenta { get; set; }
        public string tipo_cuenta { get; set; }
        public string moneda_simbolo { get; set; }
        public decimal saldo_inicial { get; set; }
        public decimal saldo_actual { get; set; }
        public System.DateTime fecha_apertura { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
        public short estado { get; set; }
        public int Tipo_moneda_id { get; set; }
        public Nullable<int> Centro_Costos_id { get; set; }
        public Nullable<int> Categoria_presupuestaria_id { get; set; }
        public int Empresa_Emp_id { get; set; }
        public int Usuarios_Usuario_id { get; set; }
    
        public virtual Categoria_presupuestaria Categoria_presupuestaria { get; set; }
        public virtual Centro_Costos Centro_Costos { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Tipo_moneda Tipo_moneda { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bancos_Movimientos> Bancos_Movimientos { get; set; }
    }
}
