//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bancos_Movimientos
    {
        public int id { get; set; }
        public int Bancos_id { get; set; }
        public short tipo_movimiento { get; set; }
        public string descripcion { get; set; }
        public decimal monto { get; set; }
        public decimal saldo_anterior { get; set; }
        public decimal saldo_posterior { get; set; }
        public short mes { get; set; }
        public string anio { get; set; }
        public System.DateTime fecha_movimiento { get; set; }
        public string referencia { get; set; }
        public Nullable<int> Centro_Costos_id { get; set; }
        public Nullable<int> Categoria_presupuestaria_id { get; set; }
        public int Tipo_moneda_id { get; set; }
        public Nullable<int> Gastos_id { get; set; }
        public Nullable<int> Ingresos_id { get; set; }
        public Nullable<int> Facturas_id { get; set; }
        public int Usuarios_Usuario_id { get; set; }
        public string Observaciones { get; set; }
        public short activo { get; set; }
    
        public virtual Categoria_presupuestaria Categoria_presupuestaria { get; set; }
        public virtual Centro_Costos Centro_Costos { get; set; }
        public virtual Facturas Facturas { get; set; }
        public virtual Gastos Gastos { get; set; }
        public virtual Ingresos Ingresos { get; set; }
        public virtual Tipo_moneda Tipo_moneda { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Bancos Bancos { get; set; }
    }
}
