//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria_presupuestaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categoria_presupuestaria()
        {
            this.Gestion_Presupuestaria = new HashSet<Gestion_Presupuestaria>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string tipo_categoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gestion_Presupuestaria> Gestion_Presupuestaria { get; set; }
    }
}
