//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Centro_Costos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Centro_Costos()
        {
            this.Cuenta_Encabezado = new HashSet<Cuenta_Encabezado>();
            this.Gestion_Presupuestaria = new HashSet<Gestion_Presupuestaria>();
            this.Bancos = new HashSet<Bancos>();
            this.Bancos_Movimientos = new HashSet<Bancos_Movimientos>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string Nombre { get; set; }
        public string Seudonimo { get; set; }
        public Nullable<decimal> Monto_presupuesto_anual { get; set; }
        public Nullable<int> Tipo_moneda_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta_Encabezado> Cuenta_Encabezado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gestion_Presupuestaria> Gestion_Presupuestaria { get; set; }
        public virtual Tipo_moneda Tipo_moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bancos> Bancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bancos_Movimientos> Bancos_Movimientos { get; set; }
    }
}
