//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codigo_actividad
    {
        public codigo_actividad()
        {
            this.Clientes = new HashSet<Clientes>();
            this.Proveedor = new HashSet<Proveedor>();
            this.Empresa = new HashSet<Empresa>();
        }
    
        public int id { get; set; }
        public string codigo_actividad1 { get; set; }
        public string nombre_actividad { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual ICollection<Proveedor> Proveedor { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
    }
}
