//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codigos_cabys
    {
        public Codigos_cabys()
        {
            this.Factura_Detalles = new HashSet<Factura_Detalles>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string Nombre { get; set; }
        public int Impuesto_id { get; set; }
    
        public virtual Impuesto Impuesto { get; set; }
        public virtual ICollection<Factura_Detalles> Factura_Detalles { get; set; }
    }
}
