//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta_Encabezado
    {
        public Cuenta_Encabezado()
        {
            this.Cuenta_Detalle = new HashSet<Cuenta_Detalle>();
        }
    
        public int id { get; set; }
        public System.DateTime Vigencia_inicial { get; set; }
        public System.DateTime Vigencia_final { get; set; }
        public int Tipo_moneda_id { get; set; }
        public int Medio_pago_id { get; set; }
        public double Total { get; set; }
        public double Monto_Proyeccion { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
        public System.DateTime Ultima_Fecha_actualizacion { get; set; }
        public int Usuarios_Usuario_id { get; set; }
        public int Facturas_id { get; set; }
        public string Referencia { get; set; }
        public int Clientes_id { get; set; }
        public double impuesto { get; set; }
        public double subtotal { get; set; }
        public short Estado { get; set; }
        public int Tipo_cuentas_id { get; set; }
        public int Cuentas_Contables_id { get; set; }
        public int Centro_Costos_id { get; set; }
        public int Gastos_id { get; set; }
    
        public virtual Centro_Costos Centro_Costos { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual ICollection<Cuenta_Detalle> Cuenta_Detalle { get; set; }
        public virtual Cuentas_Contables Cuentas_Contables { get; set; }
        public virtual Gastos Gastos { get; set; }
        public virtual Tipo_cuentas Tipo_cuentas { get; set; }
        public virtual Facturas Facturas { get; set; }
        public virtual Medio_pago Medio_pago { get; set; }
        public virtual Tipo_moneda Tipo_moneda { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
