//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta_Detalle
    {
        public int id { get; set; }
        public int Cuenta_Encabezado_id { get; set; }
        public short Tipo_movimiento { get; set; }
        public decimal monto { get; set; }
        public decimal saldo_anterior { get; set; }
        public decimal saldo_posterior { get; set; }
        public System.DateTime fecha_movimiento { get; set; }
        public string referencia_pago { get; set; }
        public string Observaciones { get; set; }
        public short activo { get; set; }
        public int Usuarios_Usuario_id { get; set; }
        public int Medio_pago_id { get; set; }
    
        public virtual Cuenta_Encabezado Cuenta_Encabezado { get; set; }
        public virtual Medio_pago Medio_pago { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
