//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas_Contables
    {
        public Cuentas_Contables()
        {
            this.Cuenta_Encabezado = new HashSet<Cuenta_Encabezado>();
        }
    
        public int id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public int Tipo_Cuenta_Contable_id { get; set; }
        public int Usuarios_Usuario_id { get; set; }
        public short Estado { get; set; }
        public double Saldo_inicial { get; set; }
        public double Saldo_actual { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public System.DateTime Fecha_actualizacion { get; set; }
    
        public virtual ICollection<Cuenta_Encabezado> Cuenta_Encabezado { get; set; }
        public virtual Tipo_Cuenta_Contable Tipo_Cuenta_Contable { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
