//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta_Detalle
    {
        public int id { get; set; }
        public double Total { get; set; }
        public double Monto_Proyeccion { get; set; }
        public double Fecha_creacion { get; set; }
        public short Estado { get; set; }
        public double Impuesto { get; set; }
        public double Subtotal { get; set; }
        public int Cuenta_Encabezado_id { get; set; }
    
        public virtual Cuenta_Encabezado Cuenta_Encabezado { get; set; }
    }
}
