//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Usuarios = new HashSet<Usuarios>();
            this.Padron = new HashSet<Padron>();
            this.Bancos = new HashSet<Bancos>();
            this.AuditaTabla = new HashSet<AuditaTabla>();
        }
    
        public int Emp_id { get; set; }
        public string Nombre_empresa { get; set; }
        public string Correo_empresa { get; set; }
        public string Ruta_nas { get; set; }
        public int Numero_sucursal { get; set; }
        public string Formato_fecha { get; set; }
        public string Ruta_llave_factura { get; set; }
        public string pin_llave { get; set; }
        public string ruta_logo { get; set; }
        public int terminal { get; set; }
        public string codigo_seguridad { get; set; }
        public string identificacion { get; set; }
        public Nullable<int> codigo_actividad_id { get; set; }
        public int tipo_identificacion_id { get; set; }
        public Nullable<int> Impuesto_id { get; set; }
        public string Correo_smtp { get; set; }
        public string Contrasena_smtp { get; set; }
        public string Proveedor_SMTP { get; set; }
        public string Puerto_SMTP { get; set; }
        public string Asunto_SMTP { get; set; }
        public Nullable<int> Distrito_id { get; set; }
        public Nullable<int> Canton_id { get; set; }
        public Nullable<int> Provincia_id { get; set; }
        public string OtrasSenas { get; set; }
        public string Telefono { get; set; }
        public string Codigo_telefono { get; set; }
        public string Usuario_hacienda { get; set; }
        public string Contrasena_hacienda { get; set; }
    
        public virtual codigo_actividad codigo_actividad { get; set; }
        public virtual Impuesto Impuesto { get; set; }
        public virtual tipo_identificacion tipo_identificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Padron> Padron { get; set; }
        public virtual Provincia Provincia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bancos> Bancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditaTabla> AuditaTabla { get; set; }
    }
}
