//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int Emp_id { get; set; }
        public string Nombre_empresa { get; set; }
        public string Correo_empresa { get; set; }
        public string Ruta_nas { get; set; }
        public int Numero_sucursal { get; set; }
        public string Formato_fecha { get; set; }
        public string Ruta_llave_factura { get; set; }
        public string pin_llave { get; set; }
        public string ruta_logo { get; set; }
        public int terminal { get; set; }
        public string codigo_seguridad { get; set; }
        public string identificacion { get; set; }
        public int codigo_actividad_id { get; set; }
        public int tipo_identificacion_id { get; set; }
        public int Impuesto_id { get; set; }
    
        public virtual codigo_actividad codigo_actividad { get; set; }
        public virtual Impuesto Impuesto { get; set; }
        public virtual tipo_identificacion tipo_identificacion { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
