//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesModel : DbContext
    {
        public EntitiesModel()
            : base("name=EntitiesModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adjuntos> Adjuntos { get; set; }
        public virtual DbSet<Canton> Canton { get; set; }
        public virtual DbSet<Categoria_gasto> Categoria_gasto { get; set; }
        public virtual DbSet<Categoria_presupuestaria> Categoria_presupuestaria { get; set; }
        public virtual DbSet<Centro_Costos> Centro_Costos { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<codigo_actividad> codigo_actividad { get; set; }
        public virtual DbSet<Codigo_comercial> Codigo_comercial { get; set; }
        public virtual DbSet<Codigos_cabys> Codigos_cabys { get; set; }
        public virtual DbSet<Condicion_venta> Condicion_venta { get; set; }
        public virtual DbSet<Devoluciones> Devoluciones { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Estado_Factura> Estado_Factura { get; set; }
        public virtual DbSet<Gastos> Gastos { get; set; }
        public virtual DbSet<Gestion_P_detalle> Gestion_P_detalle { get; set; }
        public virtual DbSet<Gestion_Presupuestaria> Gestion_Presupuestaria { get; set; }
        public virtual DbSet<Impuesto> Impuesto { get; set; }
        public virtual DbSet<Ingresos_Detalle> Ingresos_Detalle { get; set; }
        public virtual DbSet<Medio_pago> Medio_pago { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Permisos_x_rol> Permisos_x_rol { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Tablas_referencia> Tablas_referencia { get; set; }
        public virtual DbSet<Telefonos> Telefonos { get; set; }
        public virtual DbSet<Tipo_archivo> Tipo_archivo { get; set; }
        public virtual DbSet<Tipo_cambio> Tipo_cambio { get; set; }
        public virtual DbSet<Tipo_cuentas> Tipo_cuentas { get; set; }
        public virtual DbSet<Tipo_documento> Tipo_documento { get; set; }
        public virtual DbSet<tipo_identificacion> tipo_identificacion { get; set; }
        public virtual DbSet<Tipo_moneda> Tipo_moneda { get; set; }
        public virtual DbSet<Unidad_medida> Unidad_medida { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Padron> Padron { get; set; }
        public virtual DbSet<Gastos_Detalles> Gastos_Detalles { get; set; }
        public virtual DbSet<Ingresos> Ingresos { get; set; }
        public virtual DbSet<Factura_Detalles> Factura_Detalles { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Gestion_P_Anio> Gestion_P_Anio { get; set; }
        public virtual DbSet<AuditaTabla> AuditaTabla { get; set; }
        public virtual DbSet<MultiFactor> MultiFactor { get; set; }
        public virtual DbSet<Bancos_Movimientos> Bancos_Movimientos { get; set; }
        public virtual DbSet<Cuenta_Detalle> Cuenta_Detalle { get; set; }
        public virtual DbSet<Cuenta_Encabezado> Cuenta_Encabezado { get; set; }
        public virtual DbSet<Bancos> Bancos { get; set; }
    }
}
