//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_Detalles
    {
        public int id { get; set; }
        public int Facturas_id { get; set; }
        public double Subtotal { get; set; }
        public double Impuesto { get; set; }
        public double Total { get; set; }
        public int Cantidad { get; set; }
        public string Detalle { get; set; }
        public int Codigos_cabys_id { get; set; }
        public string Codigos_cabys_codigo { get; set; }
        public int Codigos_cabys_Impuesto_id { get; set; }
        public double Descuento { get; set; }
        public int Unidad_medida_id { get; set; }
        public int Codigo_comercial_id { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Ultima_fec_actualizacion { get; set; }
        public Nullable<int> Impuesto_id { get; set; }
        public Nullable<int> Tipo_Descuento_id { get; set; }
    
        public virtual Codigo_comercial Codigo_comercial { get; set; }
        public virtual Codigos_cabys Codigos_cabys { get; set; }
        public virtual Facturas Facturas { get; set; }
        public virtual Unidad_medida Unidad_medida { get; set; }
    }
}
