//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public Facturas()
        {
            this.Cuenta_Encabezado = new HashSet<Cuenta_Encabezado>();
            this.Factura_Detalles = new HashSet<Factura_Detalles>();
            this.Ingresos = new HashSet<Ingresos>();
        }
    
        public int id { get; set; }
        public string Clave { get; set; }
        public string Consecutivo_electronico { get; set; }
        public System.DateTime fecha { get; set; }
        public int consecutivo { get; set; }
        public int Tipo_moneda_id { get; set; }
        public int Estado_Factura_id { get; set; }
        public int Tipo_documento_id { get; set; }
        public double Subtotal { get; set; }
        public double Impuesto { get; set; }
        public double Total { get; set; }
        public double Descuento { get; set; }
        public int Impuesto_id { get; set; }
        public double cambio_venta { get; set; }
        public double cambio_compra { get; set; }
        public int Clientes_id { get; set; }
        public int Condicion_venta_id { get; set; }
        public int Medio_pago_id { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Condicion_venta Condicion_venta { get; set; }
        public virtual ICollection<Cuenta_Encabezado> Cuenta_Encabezado { get; set; }
        public virtual Estado_Factura Estado_Factura { get; set; }
        public virtual ICollection<Factura_Detalles> Factura_Detalles { get; set; }
        public virtual Impuesto Impuesto1 { get; set; }
        public virtual Tipo_documento Tipo_documento { get; set; }
        public virtual Tipo_moneda Tipo_moneda { get; set; }
        public virtual Medio_pago Medio_pago { get; set; }
        public virtual ICollection<Ingresos> Ingresos { get; set; }
    }
}
