//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gastos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gastos()
        {
            this.Gastos_Detalles = new HashSet<Gastos_Detalles>();
            this.Gestion_P_detalle = new HashSet<Gestion_P_detalle>();
            this.Bancos_Movimientos = new HashSet<Bancos_Movimientos>();
            this.Cuenta_Encabezado = new HashSet<Cuenta_Encabezado>();
        }
    
        public int id { get; set; }
        public string Descripcion { get; set; }
        public int Categoria_gasto_id { get; set; }
        public double Subtotal { get; set; }
        public double Impuesto { get; set; }
        public double Total { get; set; }
        public string Doc_Referencia { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Ultima_Fec_Actualizacion { get; set; }
        public int Usuarios_Usuario_id { get; set; }
        public int Tipo_documento_id { get; set; }
        public int Medio_pago_id { get; set; }
        public int Proveedor_id { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<int> Tipo_moneda_id { get; set; }
        public Nullable<int> Condicion_venta_id { get; set; }
    
        public virtual Categoria_gasto Categoria_gasto { get; set; }
        public virtual Medio_pago Medio_pago { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Tipo_documento Tipo_documento { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gastos_Detalles> Gastos_Detalles { get; set; }
        public virtual Tipo_moneda Tipo_moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gestion_P_detalle> Gestion_P_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bancos_Movimientos> Bancos_Movimientos { get; set; }
        public virtual Condicion_venta Condicion_venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta_Encabezado> Cuenta_Encabezado { get; set; }
        public string presupuesto_id { get; set; }
        public int dias_credito { get; set; }
    }
}
