//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestion_Presupuestaria
    {
        public Gestion_Presupuestaria()
        {
            this.Gestion_P_detalle = new HashSet<Gestion_P_detalle>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string Descripcion { get; set; }
        public string anio_presupuesto { get; set; }
        public System.DateTime periodo_inicio { get; set; }
        public System.DateTime periodo_fin { get; set; }
        public int Categoria_presupuestaria_id { get; set; }
        public double monto_aprobado { get; set; }
        public double monto_modificado { get; set; }
        public double monto_comprometido { get; set; }
        public double monto_ejecutado { get; set; }
        public short estado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
        public int Usuarios_Usuario_id { get; set; }
        public int Centro_Costos_id { get; set; }
    
        public virtual Categoria_presupuestaria Categoria_presupuestaria { get; set; }
        public virtual Centro_Costos Centro_Costos { get; set; }
        public virtual ICollection<Gestion_P_detalle> Gestion_P_detalle { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
