//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestion_P_detalle
    {
        public int id { get; set; }
        public double Monto { get; set; }
        public double Monto_aprobado { get; set; }
        public double Monto_modificado { get; set; }
        public double Monto_compometido { get; set; }
        public string detalle_presupuesto { get; set; }
        public int Gestion_Presupuestaria_id { get; set; }
        public Nullable<int> Categoria_presupuestaria_id { get; set; }
        public Nullable<int> Gastos_id { get; set; }
        public Nullable<int> Ingresos_id { get; set; }
        public Nullable<int> Facturas_id { get; set; }
        public decimal Monto_ejecutado { get; set; }
        public int Usuarios_Usuario_id { get; set; }
        public System.DateTime Fecha_registro { get; set; }
        public string Observaciones { get; set; }
        public short activo { get; set; }
    
        public virtual Gestion_Presupuestaria Gestion_Presupuestaria { get; set; }
        public virtual Categoria_presupuestaria Categoria_presupuestaria { get; set; }
        public virtual Gastos Gastos { get; set; }
        public virtual Ingresos Ingresos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Facturas Facturas { get; set; }
    }
}
