//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impuesto
    {
        public Impuesto()
        {
            this.Codigos_cabys = new HashSet<Codigos_cabys>();
            this.Empresa = new HashSet<Empresa>();
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public double Porcentaje { get; set; }
        public string codigo { get; set; }
    
        public virtual ICollection<Codigos_cabys> Codigos_cabys { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
