//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingresos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingresos()
        {
            this.Devoluciones = new HashSet<Devoluciones>();
            this.Ingresos_Detalle = new HashSet<Ingresos_Detalle>();
        }
    
        public int id { get; set; }
        public string Codigo { get; set; }
        public System.DateTime fecha { get; set; }
        public int Tipo_moneda_id { get; set; }
        public int Estado_Factura_id { get; set; }
        public double Subtotal { get; set; }
        public double Impuesto { get; set; }
        public double Total { get; set; }
        public double Descuento { get; set; }
        public double cambio_venta { get; set; }
        public double cambio_compra { get; set; }
        public int Clientes_id { get; set; }
        public int Usuarios_Usuario_id { get; set; }
        public int Medio_pago_id { get; set; }
        public int Facturas_id { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devoluciones> Devoluciones { get; set; }
        public virtual Estado_Factura Estado_Factura { get; set; }
        public virtual Facturas Facturas { get; set; }
        public virtual Tipo_moneda Tipo_moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingresos_Detalle> Ingresos_Detalle { get; set; }
        public virtual Medio_pago Medio_pago { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
