//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingresos_Detalle
    {
        public int id { get; set; }
        public double Subtotal { get; set; }
        public double Impuesto { get; set; }
        public double Total { get; set; }
        public int Cantidad { get; set; }
        public string Detalle { get; set; }
        public double Descuento { get; set; }
        public string codigo_comercial { get; set; }
        public int Unidad_medida_id { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Ultima_fec_actualizacion { get; set; }
        public int Ingresos_id { get; set; }
    
        public virtual Ingresos Ingresos { get; set; }
        public virtual Unidad_medida Unidad_medida { get; set; }
    }
}
