//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class marsh_contableEntities : DbContext
    {
        public marsh_contableEntities()
            : base("name=marsh_contableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adjuntos> Adjuntos { get; set; }
        public DbSet<Canton> Canton { get; set; }
        public DbSet<Categoria_gasto> Categoria_gasto { get; set; }
        public DbSet<Categoria_presupuestaria> Categoria_presupuestaria { get; set; }
        public DbSet<Centro_Costos> Centro_Costos { get; set; }
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<codigo_actividad> codigo_actividad { get; set; }
        public DbSet<Codigo_comercial> Codigo_comercial { get; set; }
        public DbSet<Codigos_cabys> Codigos_cabys { get; set; }
        public DbSet<Condicion_venta> Condicion_venta { get; set; }
        public DbSet<Cuenta_Detalle> Cuenta_Detalle { get; set; }
        public DbSet<Cuenta_Encabezado> Cuenta_Encabezado { get; set; }
        public DbSet<Cuentas_Contables> Cuentas_Contables { get; set; }
        public DbSet<Devoluciones> Devoluciones { get; set; }
        public DbSet<Distrito> Distrito { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<Estado_Factura> Estado_Factura { get; set; }
        public DbSet<Factura_Detalles> Factura_Detalles { get; set; }
        public DbSet<Facturas> Facturas { get; set; }
        public DbSet<Gastos> Gastos { get; set; }
        public DbSet<Gastos_Detalles> Gastos_Detalles { get; set; }
        public DbSet<Gestion_P_detalle> Gestion_P_detalle { get; set; }
        public DbSet<Gestion_Presupuestaria> Gestion_Presupuestaria { get; set; }
        public DbSet<Impuesto> Impuesto { get; set; }
        public DbSet<Ingresos> Ingresos { get; set; }
        public DbSet<Ingresos_Detalle> Ingresos_Detalle { get; set; }
        public DbSet<Medio_pago> Medio_pago { get; set; }
        public DbSet<Permisos> Permisos { get; set; }
        public DbSet<Permisos_x_rol> Permisos_x_rol { get; set; }
        public DbSet<Proveedor> Proveedor { get; set; }
        public DbSet<Provincia> Provincia { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Tablas_referencia> Tablas_referencia { get; set; }
        public DbSet<Telefonos> Telefonos { get; set; }
        public DbSet<Tipo_archivo> Tipo_archivo { get; set; }
        public DbSet<Tipo_cambio> Tipo_cambio { get; set; }
        public DbSet<Tipo_Cuenta_Contable> Tipo_Cuenta_Contable { get; set; }
        public DbSet<Tipo_cuentas> Tipo_cuentas { get; set; }
        public DbSet<Tipo_documento> Tipo_documento { get; set; }
        public DbSet<tipo_identificacion> tipo_identificacion { get; set; }
        public DbSet<Tipo_moneda> Tipo_moneda { get; set; }
        public DbSet<Unidad_medida> Unidad_medida { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
