//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiFactor
    {
        public int id { get; set; }
        public string OTP { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Usuarios_Usuario_id { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
