//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos_x_rol
    {
        public int id { get; set; }
        public int Permisos_id { get; set; }
        public int Roles_id { get; set; }
    
        public virtual Permisos Permisos { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
