//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.Permisos_x_rol = new HashSet<Permisos_x_rol>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int id { get; set; }
        public int Descripcion { get; set; }
    
        public virtual ICollection<Permisos_x_rol> Permisos_x_rol { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
