//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablas_referencia
    {
        public Tablas_referencia()
        {
            this.Adjuntos = new HashSet<Adjuntos>();
        }
    
        public int id { get; set; }
        public string Nombre_tabla { get; set; }
    
        public virtual ICollection<Adjuntos> Adjuntos { get; set; }
    }
}
