//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonos
    {
        public int id { get; set; }
        public string Numero { get; set; }
        public string codigo_pais { get; set; }
        public int Clientes_id { get; set; }
        public int Proveedor_id { get; set; }
        public short telefono_principal { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
