//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_moneda
    {
        public Tipo_moneda()
        {
            this.Cuenta_Encabezado = new HashSet<Cuenta_Encabezado>();
            this.Facturas = new HashSet<Facturas>();
            this.Ingresos = new HashSet<Ingresos>();
            this.Tipo_cambio = new HashSet<Tipo_cambio>();
        }
    
        public int id { get; set; }
        public string codigo_moneda { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Cuenta_Encabezado> Cuenta_Encabezado { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual ICollection<Ingresos> Ingresos { get; set; }
        public virtual ICollection<Tipo_cambio> Tipo_cambio { get; set; }
    }
}
