//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_documento
    {
        public Tipo_documento()
        {
            this.Facturas = new HashSet<Facturas>();
            this.Gastos = new HashSet<Gastos>();
        }
    
        public int id { get; set; }
        public string Codigo_doc { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual ICollection<Gastos> Gastos { get; set; }
    }
}
