//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Cuenta_Contable
    {
        public Tipo_Cuenta_Contable()
        {
            this.Cuentas_Contables = new HashSet<Cuentas_Contables>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Naturaleza { get; set; }
    
        public virtual ICollection<Cuentas_Contables> Cuentas_Contables { get; set; }
    }
}
