//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_cambio
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public double compra { get; set; }
        public double venta { get; set; }
        public int Tipo_moneda_id { get; set; }
        public int Usuarios_Usuario_id { get; set; }
    
        public virtual Tipo_moneda Tipo_moneda { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
