//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidad_medida
    {
        public Unidad_medida()
        {
            this.Factura_Detalles = new HashSet<Factura_Detalles>();
            this.Ingresos_Detalle = new HashSet<Ingresos_Detalle>();
        }
    
        public int id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Factura_Detalles> Factura_Detalles { get; set; }
        public virtual ICollection<Ingresos_Detalle> Ingresos_Detalle { get; set; }
    }
}
