//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Adjuntos = new HashSet<Adjuntos>();
            this.Cuenta_Encabezado = new HashSet<Cuenta_Encabezado>();
            this.Cuentas_Contables = new HashSet<Cuentas_Contables>();
            this.Gastos = new HashSet<Gastos>();
            this.Gestion_Presupuestaria = new HashSet<Gestion_Presupuestaria>();
            this.Ingresos = new HashSet<Ingresos>();
            this.Tipo_cambio = new HashSet<Tipo_cambio>();
        }
    
        public int Usuario_id { get; set; }
        public int Empresa_Emp_id { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Correo { get; set; }
        public string Contrasena { get; set; }
        public int Roles_id { get; set; }
        public string Id_Empleado { get; set; }
        public short activo { get; set; }
    
        public virtual ICollection<Adjuntos> Adjuntos { get; set; }
        public virtual ICollection<Cuenta_Encabezado> Cuenta_Encabezado { get; set; }
        public virtual ICollection<Cuentas_Contables> Cuentas_Contables { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Gastos> Gastos { get; set; }
        public virtual ICollection<Gestion_Presupuestaria> Gestion_Presupuestaria { get; set; }
        public virtual ICollection<Ingresos> Ingresos { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Tipo_cambio> Tipo_cambio { get; set; }
    }
}
