//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marsh_contable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Adjuntos = new HashSet<Adjuntos>();
            this.Gastos = new HashSet<Gastos>();
            this.Gestion_Presupuestaria = new HashSet<Gestion_Presupuestaria>();
            this.Tipo_cambio = new HashSet<Tipo_cambio>();
            this.Ingresos = new HashSet<Ingresos>();
            this.Gestion_P_detalle = new HashSet<Gestion_P_detalle>();
            this.Facturas = new HashSet<Facturas>();
            this.MultiFactor = new HashSet<MultiFactor>();
            this.Bancos_Movimientos = new HashSet<Bancos_Movimientos>();
            this.Cuenta_Detalle = new HashSet<Cuenta_Detalle>();
            this.Cuenta_Encabezado = new HashSet<Cuenta_Encabezado>();
            this.Bancos = new HashSet<Bancos>();
        }
    
        public int Usuario_id { get; set; }
        public int Empresa_Emp_id { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Correo { get; set; }
        public string Contrasena { get; set; }
        public int Roles_id { get; set; }
        public string Id_Empleado { get; set; }
        public short activo { get; set; }
        public Nullable<System.DateTime> Fec_creacion { get; set; }
        public Nullable<System.DateTime> Fec_Actualizacion { get; set; }
        public Nullable<System.DateTime> Fec_Login { get; set; }
        public string Codigo_recupera_clave { get; set; }
        public int Intentos_fallidos { get; set; }
        public Nullable<System.DateTime> Fecha_bloqueo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjuntos> Adjuntos { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gastos> Gastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gestion_Presupuestaria> Gestion_Presupuestaria { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipo_cambio> Tipo_cambio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingresos> Ingresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gestion_P_detalle> Gestion_P_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MultiFactor> MultiFactor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bancos_Movimientos> Bancos_Movimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta_Detalle> Cuenta_Detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta_Encabezado> Cuenta_Encabezado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bancos> Bancos { get; set; }
    }
}
